### ISSUE TITLE
Postgres should have default login

### ISSUE THREAD

**Issue by ben833** [pagerinc/composer#15]
The `test/models` tests in api-users and api-telemedicine rely on the default postgres login, which is `postgres` user and no password. In Jenkins, that credential is available, so that's why the tests pass for these repos.

**Comment by cilindrox** [comment]
Jenkins uses [default container settings](https://github.com/pagerinc/jenkins-pipeline-scripts/blob/master/src/com/pager/utils/PodTemplates.groovy#L43-L47)
